version: '3'
services:
  app:
    build: .
    container_name: node-express-server-rest-api-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

